In [ ]:
#Bar Chart of the duration of sightings per state (Year on y-axis and Duration on the x-axis)

In [1]:
import os
import pandas as pd
import matplotlib as plt
from datetime import datetime

file_path = ("Resources/ufo_clean.csv")

ufo_df = pd.read_csv(file_path)

ufo_df.head()

,Unnamed: 0,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111
1,3,10/10/1956 21:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833
2,4,10/10/1960 20:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611
3,5,10/10/1961 19:00,bristol,tn,us,sphere,300.0,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595000,-82.188889
4,7,10/10/1965 23:45,norwalk,ct,us,disk,1200.0,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.117500,-73.408333

In [5]:
#clean up df - only need datetime, state, duration (seconds)

ufo_df["datetime"].dtype

ufo_df["datetime"] = pd.to_datetime(ufo_df["datetime"])

ValueError: hour must be in 0..23